### PR TITLE
raise error if attachment pathname contains invalid bytes

### PR DESCRIPTION
**Pull request by Esther-Goldberg**
safe_path is used for input, to parse a file path from the dict. This error is occurring when doing the reverse. This change throws an EvalError if any file created by the Python code isn't able to be encoded in UTF-8.

### CODE REVIEW

**Comment by Esther-Goldberg** [comment]
This would close #205

**Comment by Esther-Goldberg** [comment]
Sure! I'll add that once I get it done

**Comment by Esther-Goldberg** [comment]
Is a test for the error returned by nsjail enough, or should the function that creates files from paths also have a test?

**Comment by MarkKoz** [comment]
That test is sufficient - it's what I also had in mind. However, the test is failing in CI.

**Review by MarkKoz — APPROVED** [review]

**Pull request merged**
