### PR TITLE
Rewrite README

### PR DESCRIPTION
**Pull request by MarkKoz**
Let me know if you think anything is missing or unclear.

I've also done some miscellaneous fixes and improvements to the scripts.

### CODE REVIEW

**Comment by SebastiaanZ** [comment]
This looks good to me. The README is clear, the only thing I'm less sure about is how a dev set-up of Snekbox is supposed to interact with a dev set-up of the bot/site running: Does this work out of the box or do we need to set up something in addition to the steps mentioned in the README?

(That question probably shows my ignorance of the subject.)

**Comment by MarkKoz** [comment]
This is a standalone program. The bot depends on snekbox, but snekbox does not depend on the bot. You could manually send POST requests to snekbox if you want. Do you think I should make this clearer in the README?

**Comment by SebastiaanZ** [comment]
No, I don't think so; I don't think it directly related to Snekbox by itself.

I was mainly thinking about the case in which someone wants to set up a complete development environment locally for the bot (which includes site) with Snekbox. Is that possible? Or would that still be difficult? Regardless, the information on how to do that should probably live in the bot's documentation, not Snekbox.

**Comment by MarkKoz** [comment]
Yes it's possible and simple. The instructions for setting up snekbox wouldn't really change at all if you needed to use it with the bot.

You did remind me that I should document the API endpoint though.

**Comment by MarkKoz** [comment]
There's a substantial amount of text here https://github.com/python-discord/snekbox/blob/2d1a0ec4a9fa7cf0758e8cc75a42cf93c1d23ebc/snekbox/api/resources/eval.py#L38

Should I just post a link to it in the README or add it to the wiki? I'm not keen on copy pasting the whole thing into the README.

**Comment by SebastiaanZ** [comment]
I think a link in the README should suffice, even if it's just a reference/link to the relevant lines in the file. I'd rather keep it DRY and link to the information, then copy-pasting it around. That also makes sure that the information is in sync, instead of having two copies floating around that could get out of sync with each other.

**Pull request merged**
