### PR TITLE
Excluded the snekbox/config_pb2.py from coverage

### LINKED ISSUE #128: Exclude config_pb2.py from coverage
It's just generated protobuf code - no need to have it under coverage.

### PR DESCRIPTION
**Pull request by Nightfurex**
Fixes #128

### CODE REVIEW

**Comment by MarkKoz** [comment]
You didn't have to create a new PR. Did you close it on accident or something? I could've re-opened if you asked.

**Comment by Nightfurex** [comment]
> You didn't have to create a new PR. Did you close it on accident or something? I could've re-opened if you asked.

Really sorry about that i accidently closed it.

**Comment by MarkKoz** [comment]
That's okay. Did you understand my comment regarding your PR description?

**Comment by Nightfurex** [comment]
> That's okay. Did you understand my comment regarding your PR description?
I new to github so i really did'nt get that part regarding PR description.

**Comment by MarkKoz** [comment]
I edited your description so you can see what I meant.

Anyway, notice that at the bottom it says one of the checks failed. Let me give you a run down of how to diagnose this. If you click on "Details" to the left of "Lint, Test, Build, Push / lint-test-build-push (pull_request)", it'll take you to some logs which explain why the check failed.

bild

Once there, expand the "Run pre-commit hooks" section to read the relevant logs:

bild

pre-commit is a linting tool we use. Notice that the "trim trailing whitespace" hook has failed. More specifically, the culprit was `.coveragerc`, which is the file you've edit. To fix this, you'll need to edit the file and remove any trailing whitespace. I think you have a trailing whitespace on line 4.

**Review by MarkKoz — APPROVED** [review]
Thanks!

**Pull request merged**
